export interface AddNewSupplier
{
  proprietorphonenumber:number,
    id: number,
    supplierId: number,
    supplierName: string,
    typeofFirm: string,
    proprietorName: string,
    panNumber: string,
    PanNumberImage: any[],
    addressProofType: string,
    AddressProofImage: any[],
    ChequeImage:any[],
    GSTImage:any[],
    emailId: string,
    mobileNo: number,
    creditScore: number,
    fatherName: string,
    isLoanRequirement: boolean,
    loanAmount: number,
    supplierType: string,
    SupplierSegment:string;
    ContactPersonMobileNo:number,
    // sellingBrands: any[],
    SellingBrandDCs:any[],
    Stateid: number,
      StateName: string,
      Cityid: number,
      CityName: string,
      City:string;
    // businessEstablishmentYear: Date,
    businessEstablishmentYear: number,
    gstinno: string,
    FSSAINO: string,
    FSSAIImage: any[],
    fullBusinessAddress: string,
    headOffice: string,
    pinCode: number,
    bankAccType: string,
    bankAccNo: number,
    bankAddress: string,
    bankName: string,
    bankPinCode:number,
    ifscCode: string,
    userid: number,
    Comments: string,
    suppliercodes: string,
    Status:boolean;
    isStopAdvancePr: boolean,
  isIRNInvoiceRequired: boolean,
  password: any,
  webUrl: any,
  contactPerson: any,
  bussinessType: any,
  StartedBusiness: any,
  paymentTerms: any,
  Message:string,
  ProprietorPanNumber:string,
  AgreementImage:any[],
  ProprietorPanImage:any[],
  ExpiryDays:any,
  // --created  by anjali
  IsVerified:boolean,
  Active:boolean,
  Deleted:boolean,
  PanNumberImages:any[],
  AddressProofImages:any[],
  AgreementImages :any[],
  ChequeImages:any[],
  FSSAIImages :any[],
  GSTImages:any[],
  ProprietorPanImages :any[]
  MSMEImage:any[];
  MSMEType:string;
  BuyerId: 0;
  BuyerName: null;
}